version: '3.7'  # Aktualisieren Sie die Version für bessere Funktionalität

services:
  pihole1:
    container_name: pihole1
    image: pihole/pihole:latest
    networks:
      dns_network:
        ipv4_address: 172.24.0.3
    ports:
      - "8081:80"  # Pi-hole 1 auf Port 8081
    environment:
      WEBPASSWORD: "Passwort123!"
    volumes:
      - "./pihole/pihole/etc/pihole/:/etc/pihole/"
      - "./pihole/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped

  pihole2:
    container_name: pihole2
    image: pihole/pihole:latest
    networks:
      dns_network:
        ipv4_address: 172.24.0.4
    ports: 
      - "8082:80"  # Pi-hole 2 auf Port 8082
    environment:
      WEBPASSWORD: "Passwort123!"
    volumes:
      - "./pihole/pihole/etc/pihole/:/etc/pihole/"
      - "./pihole/pihole/etc/dnsmasq.d/:/etc/dnsmasq.d/"
    restart: unless-stopped

  dnsdist:
    container_name: dnsdist
    image: powerdns/dnsdist-master:latest
    networks:
      dns_network:
        ipv4_address: 172.24.0.2
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./dnsdist/dnsdist.conf:/etc/dnsdist/dnsdist.conf"
    depends_on:
      - pihole1
      - pihole2
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      dns_network:
        ipv4_address: 172.24.0.5
    ports:
      - "8083:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - pihole1
      - pihole2
    restart: unless-stopped

networks:
  dns_network:
    external: true